add pek project content
kir-dev/blog-next pull request #125
Opened 2021-07-11 19:33 UTC by SepsiLaszlo

## What is new?
- Add content for PeK project
## Todo
- Add image to PeK content
- Add konyha description

2021-07-27 20:17 UTC, triszt4n requested changes

2021-07-27 20:17 UTC, triszt4n commented on src/content/projects/konyha.md
> +Ezeknek és a többi hasonló kérdésnek a megválaszolást célozza meg a projekt. Egy olyan alkalmazást szeretnénk készíteni, ahol megtekintehtő az egyes konyhákban található eszközök listája és lehet jel
megválaszolást -> megválaszolását
megtekintehtő -> megtekinthető

2021-07-27 20:17 UTC, triszt4n commented on src/content/projects/pek-next.md
> +Az alkalmazást rengetegen használják, jelenleg **több mint 26 ezer felhasználóval** rendelkezik az oldal. Emellett sok összetett folyamatot valósít meg az alkalmazás, amiket gyakran az aktuális igény
szemelőtt -> szem előtt
jólműködő -> jól működő

2021-07-30 06:01 UTC, SepsiLaszlo commented on src/content/projects/konyha.md
> +Ezeknek és a többi hasonló kérdésnek a megválaszolást célozza meg a projekt. Egy olyan alkalmazást szeretnénk készíteni, ahol megtekintehtő az egyes konyhákban található eszközök listája és lehet jel
Done!

2021-07-30 07:08 UTC, triszt4n approved these changes
Nice

2021-07-30 07:10 UTC, triszt4n approved these changes

2021-07-30 07:23 UTC, merged