Improve navbar and home page
kir-dev/blog-next pull request #24
Opened 2021-04-14 23:29 UTC by triszt4n

Branch is based on `ref/post-style` because I needed the new version of some packages.

### What's new:
* Responsive, cute little navbar with better button layout
* Terminal on home page (I think we should keep it, it looks so awesome)

### Important questions:
* Talented people at hyper's project (including @vassbence) made this terminal that I customised for our blog, src: https://github.com/vercel/hyper-site
  * How should we mention their work? They have MIT licence, but I have no experience with mentioning other people's work, so help me with that.
* So I will make a full figma design later, but this is right now what I could merge from @vassbence's, @balintkiraly's and schdesign's plans for the first page:
![Screenshot from 2021-04-15 01-22-34](https://user-images.githubusercontent.com/60111772/114792902-81e0b600-9d89-11eb-8954-cb258a685a76.png)
  * Some details what I will be planning the design from:
    * Bence's members page (zoom meeting-like)
    * Kircsi's basic coloring (dark mode: schdesign's colorings)
    * Footer by schdesign
* I will post the details and plans in Slack once they're ready.

Closes #21

2021-04-15 05:50 UTC, balintkiraly commented on src/components/Navbar.tsx
> +/* eslint-disable max-len */
Would be better to split this to several files.

2021-04-15 05:55 UTC, balintkiraly commented on src/components/terminal/Terminal.tsx
> +              href="https://bit.ly/3uOVmYt"
You got me 😄

2021-04-15 10:14 UTC, OmTheTurtle commented
Merged the changes from #22 please rebase this so it'll only have the relevant changes.

2021-04-16 12:42 UTC, OmTheTurtle commented on src/components/Navbar.tsx
> +/* eslint-disable max-len */
@triszt4n This should definitely be done before merging, especially extracting the SVGs into separate files.

2021-04-16 12:42 UTC, OmTheTurtle commented on src/components/Navbar.tsx
> +/* eslint-disable max-len */
Also, we shouldn't opt-out of eslint rules for whole files, only where it makes sense.

2021-04-16 12:49 UTC, OmTheTurtle requested changes

2021-04-16 12:49 UTC, OmTheTurtle commented on src/components/Navbar.tsx
> +  const logoColor3 = '#F15A29'
Just a note, but we shouldn't use arbitrary hex values in code, either use predefined values from chakra or create a theme config and define them there is possible.

2021-04-16 12:49 UTC, OmTheTurtle commented on src/components/Navbar.tsx
> +        maxW={['100%', '100%', '720px', '1280px']}
Use em / rem instead of pixel values.

2021-04-16 12:49 UTC, OmTheTurtle commented on src/components/terminal/Terminal.tsx
> +          {lineCount >= 5 && showLine('Technológiáink közé tartozik a Node.js, a Ruby on Rails és a Spring + Kotlin.')}
I think SpringBoot is the correct name for the tech.

2021-04-16 12:49 UTC, OmTheTurtle commented on src/components/Header.tsx
> +const Header: React.FC = () => <Navbar />
Not sure if we need the extra Header component if it only renders another, I think it can be removed.

2021-05-21 00:34 UTC, triszt4n commented on src/components/Header.tsx
> +const Header: React.FC = () => <Navbar />
Done

2021-05-21 00:34 UTC, triszt4n commented on src/components/terminal/Terminal.tsx
> +          {lineCount >= 5 && showLine('Technológiáink közé tartozik a Node.js, a Ruby on Rails és a Spring + Kotlin.')}
Done

2021-05-21 00:34 UTC, triszt4n commented on src/components/Navbar.tsx
> +  const logoColor3 = '#F15A29'
Done

2021-05-21 00:34 UTC, triszt4n commented on src/components/Navbar.tsx
> +/* eslint-disable max-len */
All done

2021-05-24 20:35 UTC, triszt4n commented
Still has one flaw: can't get PéK profile pictures from `/photos/{username}` because of CORS, I might need some help with that thx

2021-05-26 14:10 UTC, OmTheTurtle commented
> Still has one flaw: can't get PéK profile pictures from `pek.sch.bme.hu/photos/{username}` because of CORS, I might need some help with that thx

That's because we don't provide the profile picture from PeK to be available on different sites. If we want to, it needs changes on PeK's codebase, so I'd skip if for now for this project.

2021-05-26 14:16 UTC, OmTheTurtle commented on src/pages/index.tsx
> +              />
Is it possible to have this image as an SVG? In dark mode the black lines aren't really visible, so I thought that with an SVG we can change them to white ones (like on the navbar logo). Also, please avoid using float if possible.

2021-05-26 18:24 UTC, triszt4n commented
> > Still has one flaw: can't get PéK profile pictures from `pek.sch.bme.hu/photos/{username}` because of CORS, I might need some help with that thx
> 
> That's because we don't provide the profile picture from PeK to be available on different sites. If we want to, it needs changes on PeK's codebase, so I'd skip if for now for this project.

Laci is helping me test it by using the staging site, gonna see if it works well soon, but yeah you're right, it will be unfolded in the production version.

2021-05-26 20:08 UTC, triszt4n commented on src/pages/index.tsx
> +              />
Done

2021-05-26 22:10 UTC, OmTheTurtle commented on src/components/blog-components/BlogAuthor.tsx
> +  const pekUrl = 'https://pek.k8s.sch.bme.hu'
This should be in some globals / constants file, and should be the live version.

2021-05-26 22:12 UTC, OmTheTurtle commented on src/components/blog-components/BlogPreview.tsx
> +interface PostForPreview {
I think a better name would be `BlogPreviewProps`

2021-05-26 22:15 UTC, OmTheTurtle commented on src/components/blog-components/BlogAuthor.tsx
> +      <Text>—</Text>
I think having the name show up somewhere here would be nice.

2021-05-26 22:21 UTC, OmTheTurtle commented on src/components/indexpage-components/InfoBox.tsx
> +      float={{ base: 'right', md: 'none' }}
Can we use something else than float?

2021-05-26 22:24 UTC, OmTheTurtle commented on src/components/navbar/MobileNav.tsx
> +              </Link>
This should be wrapped into a Gatsby link, otherwise all navigation will cause a full page load (with the light / dark mode flashing).

2021-05-26 22:24 UTC, OmTheTurtle commented on src/components/navbar/DesktopNav.tsx
> +              </Link>
This should be wrapped into a Gatsby link, otherwise all navigation will cause a full page load (with the light / dark mode flashing).

2021-05-26 22:25 UTC, OmTheTurtle commented on src/components/blog-components/BlogPreview.tsx
> +        </Link>
This should be wrapped into a Gatsby link, otherwise all navigation will cause a full page load (with the light / dark mode flashing).

2021-05-26 22:25 UTC, OmTheTurtle commented on src/components/navbar/NavItem.tsx
> +export interface NavItem {
This can be just a `.ts` file

2021-05-26 22:26 UTC, OmTheTurtle commented on src/components/navbar/Navbar.tsx
> +          </Link>
This should be wrapped into a Gatsby link, otherwise all navigation will cause a full page load (with the light / dark mode flashing).

2021-05-26 22:28 UTC, OmTheTurtle commented on src/pages/index.tsx
> +  const post = data.allMarkdownRemark.nodes[0]
```suggestion
  const [post] = data.allMarkdownRemark.nodes
```

2021-05-26 22:59 UTC, triszt4n commented on src/components/blog-components/BlogAuthor.tsx
> +      <Text>—</Text>
Lol right, some merge conflict effed it up

2021-05-26 23:01 UTC, triszt4n commented on src/components/indexpage-components/InfoBox.tsx
> +      float={{ base: 'right', md: 'none' }}
ofc, I guess some flexbox magic :sparkles: or `place-content` should do it (leaving this comment so I don't forget).

2021-05-26 23:02 UTC, triszt4n commented on src/components/navbar/MobileNav.tsx
> +              </Link>
Oh wow, so that's why the gatsby `Link` is better! I've gone with the Chakra one everywhere :disappointed: No probs, gonna mend all of them.

2021-05-26 23:04 UTC, triszt4n commented on src/pages/index.tsx
> +  const post = data.allMarkdownRemark.nodes[0]
Lol, fancy shit :art: Love it

2021-05-26 23:27 UTC, triszt4n commented on src/components/indexpage-components/InfoBox.tsx
> +      float={{ base: 'right', md: 'none' }}
So there are many unclever, disgusting workarounds with grids and nothing clean (it would need even more magic css properties). So my vote is nay for this, your honor.

2021-05-27 16:34 UTC, OmTheTurtle commented on src/components/indexpage-components/InfoBox.tsx
> +      float={{ base: 'right', md: 'none' }}
You're right, this is the exact use-case where float was designed to work, my bad :D

2021-05-27 16:43 UTC, balintkiraly commented
I think we should use an svg optimizer
 https://github.com/svg/svgo

2021-05-27 16:45 UTC, balintkiraly approved these changes

2021-05-27 16:48 UTC, OmTheTurtle approved these changes

2021-05-27 17:56 UTC, SepsiLaszlo approved these changes

2021-05-27 17:57 UTC, merged