add szakmai-het-2021 post
kir-dev/blog-next pull request #277
Opened 2021-11-26 10:32 UTC by SepsiLaszlo

2021-11-26 11:38 UTC, triszt4n requested changes
Very nice all around, könnyen olvasható és izgalmas. 🍪 
Néhány nyelvtani hibát bedobtam

2021-11-26 11:38 UTC, triszt4n commented on src/content/posts/2021-11-25-simonyi-szakmai-het-2021.md
> +featuredImage: ../images/posts/szakmai-het-cover.jpg
Ez egy elég igényes kép, úgyhogy még `ogImage`-nek is mehetne.
```suggestion
featuredImage: ../images/posts/szakmai-het-cover.jpg
ogImage: ../images/posts/szakmai-het-cover.jpg
```

2021-11-26 11:38 UTC, triszt4n commented on src/content/posts/2021-11-25-simonyi-szakmai-het-2021.md
> +Nagyon vártuk Simonyi Szakmai Hetet. Rengeteg izgalmas program és előadás volt a menetrendben. Az előadások közül több is kapcsolódott a kör profiljához, a webfejlesztéshez.
* "Nagyon vártuk **a** Simonyi ..."

2021-11-26 11:38 UTC, triszt4n commented on src/content/posts/2021-11-25-simonyi-szakmai-het-2021.md
> +A hét első napja a Szakmai Est volt, ahol a Simonyi aktív tagjai mutatták be, hogy mivel foglalkoztak az utóbbi időben. Több szakkollégiumi körből is jöttek előadók. Mi is készültünk előadással, amin
* megb**í**rkóznia -> megb**i**rkóznia

2021-11-26 11:38 UTC, triszt4n commented on src/content/posts/2021-11-25-simonyi-szakmai-het-2021.md
> +Az elsők között érkeztünk meg a Szülinap helyszínére, igy még volt asztal, ahova mindannyian le tudtunk ülni. Az utóbbi hetek nagyon mozgalmasan teltek mindenki számra, ezért kifejezetten jó volt kic
* **i**gy -> **í**gy
* mindenki számra -> mindenki szám**á**ra
* ahol a Kir-Dev-es csapat nem látszik -> ahol a Kir-Dev-es csapat nem **teljesen** látszik

2021-12-03 11:59 UTC, SepsiLaszlo commented on src/content/posts/2021-11-25-simonyi-szakmai-het-2021.md
> +featuredImage: ../images/posts/szakmai-het-cover.jpg
Ha nem adom meg explicit az ogImage-et, akkor nem lesz a feturedImage-t fogja használni automatikusan?
A README-ben ezt olvastam és localban úgy tűnik, hogy igy is történik.

2021-12-03 12:07 UTC, triszt4n commented on src/content/posts/2021-11-25-simonyi-szakmai-het-2021.md
> +featuredImage: ../images/posts/szakmai-het-cover.jpg
Very true, nem kell akkor :D

2021-12-03 12:09 UTC, triszt4n approved these changes

2021-12-03 12:12 UTC, merged