Added indulaSch description
kir-dev/blog-next pull request #294
Opened 2021-12-19 20:47 UTC by berenteb

Edited md and lead image.

2021-12-19 21:09 UTC, triszt4n requested changes
Na minden fasza, nagyon tetszik, annyi, hogy a markdown szereti, ha vannak üres sorok az egyes blokkok között, így lesz egyértelmű a parsolás.

2021-12-19 21:09 UTC, triszt4n commented on src/content/projects/indulasch.md
> +# A fő célkitűzés
A header-ök előtt és után legyen 1-1 üres sor.

2021-12-19 21:09 UTC, triszt4n commented on src/content/projects/indulasch.md
> +![2.0 app](https://warp.kir-dev.sch.bme.hu/img/blobs/redirect/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBTdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--133cebeeb425a7e39b267eddc354d9759b88b455/iPhone.png)
a képek is legyenek elkülönített sorban, azaz előttük és utánuk legyen 1-1 üres sor.

2021-12-19 21:09 UTC, triszt4n commented on src/content/projects/indulasch.md
> +Elkészült egy koncepció 2021. tavaszán, mely egy utastájékoztató kijelzőt valósított meg házilag.
2021 tavaszán (birtokviszony miatt nem kell a pont)

2021-12-19 21:09 UTC, triszt4n commented on src/content/projects/indulasch.md
> +Ugyanazon év őszén az egész projektet újraírtuk React és TypeScript alapokon. Ugyanakkor a frontend és backend külön tárolóként lett kezelve.
esetleg itt a frontend és backend szavakra lehetne link, mert a backendhez nincs a posztban sehol link. Kb így:
```md
a [frontend](https://github.com/kir-dev/indulasch-frontend) és [backend](https://github.com/kir-dev/indulasch-api) külön
```

2021-12-20 00:46 UTC, triszt4n approved these changes
Mehet is be

2021-12-20 12:13 UTC, poiuztrewq1 approved these changes
💯

2021-12-20 17:03 UTC, merged