add-kir-dev-20+-post
kir-dev/blog-next pull request #397
Opened 2022-05-12 17:47 UTC by SepsiLaszlo

2022-05-20 11:27 UTC, DannySS123 approved these changes
Great work, looking very promising! 💯 🔥 
Just some small grammar corrections.

2022-05-20 11:27 UTC, DannySS123 commented on src/content/posts/2022-05-08-kir-dev-20.md
> +A Kir-Dev 2021-ben elérte működésének 20-adik évfordulóját. Ennek a kiemelkedő mérföldkőnek a megünneplését nem szeretnénk tovább húzni. Igy idén nyáron, a Kir-Dev 20+ rendezvény formájában szeretnén
Igy idén nyáron -> Így idén nyáron

2022-05-20 11:27 UTC, DannySS123 commented on src/content/posts/2022-05-08-kir-dev-20.md
> +  - A program ezen a részén felkérjük a megjelent tagokat és öregtagokat, hogy mutatkozzanak be és néhány mondatban foglalják össze, körön belüli és körön túli tevékenységüket.
tevékenységüket -> tevékenységeiket

2022-05-20 12:30 UTC, tomitheninja commented
I think the space between the plus and the exclamation sign looks weird.
![image](https://user-images.githubusercontent.com/57364372/169528405-e4141f81-2ab7-46ea-b85f-9e91470962e9.png)

2022-05-20 12:40 UTC, tomitheninja commented
The site here feels skinny for me.

Can we replace this image with a gallery?
I think between a carousel and a full screen image scrolling system like on https://spot.sch.bme.hu

![image](https://user-images.githubusercontent.com/57364372/169528612-f6f2e706-66a2-4bf5-bfb6-dea616e0e752.png)

2022-05-20 15:38 UTC, bbucsy approved these changes
Nice!

2022-05-20 20:53 UTC, SepsiLaszlo commented
@DannySS123 thank you for the suggestions, I corrected the typos!

2022-05-20 20:55 UTC, DannySS123 approved these changes

2022-05-20 20:55 UTC, SepsiLaszlo commented
@tomitheninja I don't think there is an easy way to do what you suggested and the other posts have the same design. 
So I think we should keep this as is, and look into the possible improvemnets in the future.

2022-05-21 17:18 UTC, triszt4n requested changes
Nicely written and designed post! Please see my requests. Also: we might want to tell them, that they can ask about anything via our email address or Slack channels.

2022-05-21 17:18 UTC, triszt4n commented on src/content/posts/2022-05-08-kir-dev-20.md
> +A rendezvény a Schönherz Kollégiumban kerül megrendezésre, 2022-es nyár folyamán. A pontos időpontot szeretnék úgy megválasztani, hogy minél több öregtagunk el tudjon jönni. Ha körünk öregtaja vagy,
öregtaja -> öregtagja

2022-05-21 17:18 UTC, triszt4n commented on src/content/posts/2022-05-08-kir-dev-20.md
> +https://forms.gle/XjYcb3UKZ6RzQkR86
The form requires logging in with Google account. Is it necessary? We also require their email address, isn't that enough?

2022-05-21 17:19 UTC, triszt4n commented
> The site here feels skinny for me.
> 
> Can we replace this image with a gallery?
> I think between a carousel and a full screen image scrolling system like on https://spot.sch.bme.hu
> 
> ![image](https://user-images.githubusercontent.com/57364372/169528612-f6f2e706-66a2-4bf5-bfb6-dea616e0e752.png)
> 

@tomitheninja let's not redesign the site for now, but send an issue to the repo with your requests, thx

2022-05-22 16:51 UTC, balintkiraly commented
Maybe a few words about Schonherz's current COVID restrictions would be great for the old members (I think this can be placed in the form).
And a feedback for the form.. the question about the days should be multi-select

2022-05-24 18:54 UTC, SepsiLaszlo commented
@balintkiraly Thank you for the feedback, I made the suggested change!

2022-05-24 19:00 UTC, SepsiLaszlo commented on src/content/posts/2022-05-08-kir-dev-20.md
> +https://forms.gle/XjYcb3UKZ6RzQkR86
@triszt4n Thank you for the sharp review! :eagle:  :detective: 
I made the suggested changes!

2022-05-24 19:49 UTC, triszt4n requested changes

2022-05-24 19:49 UTC, triszt4n commented on src/content/posts/2022-05-08-kir-dev-20.md
> +lead: Megrendezésre ketül a Kir-Dev 20!
```suggestion
lead: Megrendezésre kerül a Kir-Dev 20!
```

2022-05-24 19:50 UTC, triszt4n approved these changes
All nice and good

2022-05-24 20:07 UTC, DannySS123 approved these changes
👌

2022-05-25 17:56 UTC, bbucsy approved these changes

2022-05-26 07:46 UTC, merged