add kir-dev 20 experience report
kir-dev/blog-next pull request #429
Opened 2022-09-17 15:47 UTC by SepsiLaszlo

2022-09-17 22:26 UTC, triszt4n requested changes
nyelvtan, illetve adtam linket a warpos albumokhoz

2022-09-17 22:26 UTC, triszt4n commented on src/content/posts/2022-09-17-ilyen-volt-a-kir-dev-20+!.md
> +A rendezévényről a SPOT Fotókör készítette a remek képeket, a [teljes abum megtaláljható itt](https://spot.sch.bme.hu/photo/2022/20220828_kir_dev/)!
Typo: 
- rendezévényről -> rendezvényről 
- megtaláljható -> megtalálható

2022-09-17 22:26 UTC, triszt4n commented on src/content/posts/2022-09-17-kir-dev-nyar-2022.md
> +Első lépésként, közösen meghodítottuk a Katica Tanyát. A tanyán kipróbáltuk a lábbal hajtós gokartokat, csúszdákat, labirintusokat és az ugrálóvárat is. De a kedvenc játékunk a komp volt, amit sikerü
Grammar:
- meghodítottuk -> meghódítottuk

A komphoz és SNYT-hez általában jöhetnek innen képek: https://warp.sch.bme.hu/albums/47

2022-09-17 22:26 UTC, triszt4n commented on src/content/posts/2022-09-17-kir-dev-nyar-2022.md
> +A kör a szórakozás mellett, itt sem volt tétlen. Az SNYT re is készítettünk weboldalt, amivel QR kódokat és ötletes feladatokat tudtak leadnia táborozók.
Grammar: 
- SNYT re -> SNYT-re
- leadnia -> leadni a

2022-09-17 22:26 UTC, triszt4n commented on src/content/posts/2022-09-17-kir-dev-nyar-2022.md
> +Fontos a kör számára, hogy aktív kikapcsolódásban is részt vehessenek a tagok, ezér a tábor második napján kenuzni mentünk. Nagymarostól leevesztünk első körben Verőcére, ahol megvizsgáltuk a helyi v
grammar:
- ezér -> ezért
- leevesztünk -> leeveztünk

Jöhetnek képek: https://warp.sch.bme.hu/albums/42

2022-09-17 22:26 UTC, triszt4n commented on src/content/posts/2022-09-17-kir-dev-nyar-2022.md
> +A nyáron megtartásra került a régóta várt Kir-Dev 20+ redezvény. Itt lehetőség nyílt arra, hogy a kör jelenlegi aktív tagja, találkozzanak a kör öregtagjaival és együtt megünnepljék a kör késői húsza
Grammar:
- megünnepljék -> megünnepeljék
- húszadik -> huszadik

2022-09-17 22:26 UTC, triszt4n commented on src/content/posts/2022-09-17-kir-dev-nyar-2022.md
> +A rendezvényt a körvezető nyitotta meg egy izgalmas prezentációva. Beni ismertette a kör jelenlegi helyzetét, bemuttata az aktuális projekteket és elért célokat. A körös áttekintés után időrendi sorr
Grammar:
- prezentációva -> prezentációval
- bemuttata -> bemutatta
- húszadik -> huszadik

2022-09-19 06:14 UTC, SepsiLaszlo commented on src/content/posts/2022-09-17-ilyen-volt-a-kir-dev-20+!.md
> +A rendezévényről a SPOT Fotókör készítette a remek képeket, a [teljes abum megtaláljható itt](https://spot.sch.bme.hu/photo/2022/20220828_kir_dev/)!
:heavy_check_mark:

2022-09-19 06:14 UTC, SepsiLaszlo commented on src/content/posts/2022-09-17-kir-dev-nyar-2022.md
> +Első lépésként, közösen meghodítottuk a Katica Tanyát. A tanyán kipróbáltuk a lábbal hajtós gokartokat, csúszdákat, labirintusokat és az ugrálóvárat is. De a kedvenc játékunk a komp volt, amit sikerü
:heavy_check_mark:

2022-09-19 06:16 UTC, SepsiLaszlo commented on src/content/posts/2022-09-17-kir-dev-nyar-2022.md
> +Fontos a kör számára, hogy aktív kikapcsolódásban is részt vehessenek a tagok, ezér a tábor második napján kenuzni mentünk. Nagymarostól leevesztünk első körben Verőcére, ahol megvizsgáltuk a helyi v
:heavy_check_mark:

2022-09-19 06:16 UTC, SepsiLaszlo commented on src/content/posts/2022-09-17-kir-dev-nyar-2022.md
> +A kör a szórakozás mellett, itt sem volt tétlen. Az SNYT re is készítettünk weboldalt, amivel QR kódokat és ötletes feladatokat tudtak leadnia táborozók.
:heavy_check_mark:

2022-09-19 06:18 UTC, SepsiLaszlo commented on src/content/posts/2022-09-17-kir-dev-nyar-2022.md
> +A nyáron megtartásra került a régóta várt Kir-Dev 20+ redezvény. Itt lehetőség nyílt arra, hogy a kör jelenlegi aktív tagja, találkozzanak a kör öregtagjaival és együtt megünnepljék a kör késői húsza
:heavy_check_mark:

2022-09-19 16:09 UTC, DannySS123 approved these changes
Lookin great 💯 🔥

2022-09-19 19:23 UTC, merged