Szintefestes
kir-dev/blog-next pull request #433
Opened 2022-09-30 15:02 UTC by DannySS123

2022-09-30 15:14 UTC, triszt4n requested changes
Nice stuff, see my typo requests

2022-09-30 15:14 UTC, triszt4n commented on src/content/posts/2022-09-30-szintfestes.md
> +Idén a szintfestés alól a Schönherz 13. emelete, a Simonyi szakkolléium szintje se maradhatott ki. Még egészen sok üres hely volt a falakon, így már igazán itt volt az ideje, hogy színesebbé tegyük a
* Simonyi szakkolléium -> Simonyi Károly Szakkollégium

2022-09-30 15:14 UTC, triszt4n commented on src/content/posts/2022-09-30-szintfestes.md
> +A Kir-Dev csapata is részt vett ebben. Még a szintfestés napja előtt megterveztünk és felrajzoltuk a kör logójának körvonalát, majd a várva várt napont egy kellemes délutánt töltöttek tagjaink a fest
* napont -> napon

2022-09-30 15:14 UTC, triszt4n commented on src/content/posts/2022-09-30-szintfestes.md
> +Eddig még soha nem volt Kir-Dev logó festeve a szakkoli szintjén, úgyhogy már nagyon itt volt az ideje.
* festeve -> festve

2022-09-30 15:14 UTC, triszt4n commented on src/content/posts/2022-09-30-szintfestes.md
> +Viszont a tagjaink tevékenysége a logónk befejeztével se maradt abba, úgyanis egy másik logó is nagyon hiányzott már a szintről, mégpedig a szokkollégium logója. A Simonyi sok köréből érkeztek lekes
* úgyanis -> ugyanis
* szokkollégium -> szakkollégium
* lekes -> lelkes

2022-09-30 19:03 UTC, Tschonti approved these changes

2022-09-30 19:07 UTC, SepsiLaszlo approved these changes
Great work, I feel really inspired after reading it! :rocket:

2022-10-02 14:41 UTC, triszt4n approved these changes
Let's brag about our community 👑

2022-10-02 19:26 UTC, merged