add karácsony-2021
kir-dev/blog-next pull request #448
Opened 2022-12-20 21:47 UTC by SepsiLaszlo

2022-12-21 08:22 UTC, triszt4n approved these changes

2022-12-21 09:25 UTC, Tschonti requested changes
Király lett, csak pár typo

2022-12-21 09:25 UTC, Tschonti commented on src/content/posts/2022-12-20-karacsony-2021.md
> +title: Karácsony 2021
2022

2022-12-21 09:25 UTC, Tschonti commented on src/content/posts/2022-12-20-karacsony-2021.md
> +Az ünnepi időszak közeledtével minket is utolért a Karácsony szelleme. Igy nagy lelkesedéssel vettünk részt a [SPOT Fotókör](https://spot.sch.bme.hu/) karácsonyi fotózásán, ahol számos remek kép szül
Így

ezek közül

2022-12-21 09:25 UTC, Tschonti commented on src/content/posts/2022-12-20-karacsony-2021.md
> +Ezután már csak a tészta formáravágas és megsütése volt hátra. A szokásos karácsonyi formák mellett, megpróbáltuk a kör logóját is megformázni mézeskalácsból.
formára vágása

formák mellett megpróbáltuk (nem kell vessző)

2022-12-23 12:08 UTC, SepsiLaszlo commented
@Tschonti Köszönöm Samu, hogy átolvastad és megtaláltada typo-kat, javítottam őket!

2022-12-23 12:09 UTC, merged