add felevzaro-2022
kir-dev/blog-next pull request #452
Opened 2022-12-30 14:51 UTC by SepsiLaszlo

2022-12-30 16:27 UTC, triszt4n commented
Cool :D mehet amúgy majd ez is ilyen mindenféle email címekre, hogy az öregek is lássák, élünk :D

2022-12-30 17:41 UTC, DannySS123 requested changes
Kedves László, megint csak kiváló munkát végeztél 😍 🔥 💯 🍾 

Ezt a pár apróságot találtam, ezen kívül fenomenális lett! 👌

2022-12-30 17:41 UTC, DannySS123 commented on src/content/posts/2022-12-30-felevzaro-es-b.u.É.k.---2022.md
> +Egy igazán eseményteli félévet és évet tudhatunk magunk mögött. Számos felejthetetlen élménnyel gazdagodtunk az év során valamint, rengeteg mérföldkövet is sikerült átlépnünk. Reméljük, hogy számodra
során, valamint rengeteg

2022-12-30 17:41 UTC, DannySS123 commented on src/content/posts/2022-12-30-felevzaro-es-b.u.É.k.---2022.md
> +A rendezvény a Szakest elnökválasztásával kezdődött, amit a tisztviselők kinevezése követett. Több tagunk is a tisztviselők sorát erősítette. Volt körvezetőnk, [Kircsi (Király Bálint)](https://pek.sc
Kontrapult-ban

2022-12-30 17:41 UTC, DannySS123 commented on src/content/posts/2022-12-30-felevzaro-es-b.u.É.k.---2022.md
> +Az est teli volt meglepetésekkel. A műsor egy pontján a kontrák kihívták a Kir-Dev jelenlegi és összes jelenlévő ex körvezetőjét, hogy egy sörpárbajban bizonyítsák a rátermettségüket. A résztvevők id
ex-körvezetőjét
legtapasztaltabbig

2022-12-31 09:04 UTC, SepsiLaszlo commented on src/content/posts/2022-12-30-felevzaro-es-b.u.É.k.---2022.md
> +A rendezvény a Szakest elnökválasztásával kezdődött, amit a tisztviselők kinevezése követett. Több tagunk is a tisztviselők sorát erősítette. Volt körvezetőnk, [Kircsi (Király Bálint)](https://pek.sc
Hú ez kicsit megzavart, mert én azt gondoltam, hogy ez pult, de egyszer mondta valaki, hogy ez valami Szakesetes német cucc és igy kell írni, de lehetne Contrapunct is. Nem tudom melyik a jó.
https://hu.wikipedia.org/wiki/Ellenpont
https://ombke-dunaujvaros.info/hagyomanyaink/szakestelyek/szakestelyek-tisztsegviseloi/

2022-12-31 09:07 UTC, SepsiLaszlo commented
@DannySS123 köszönöm a minőségi korrektúrát, mindent észre vesz a sas szemed! :eagle: :detective:

2022-12-31 13:30 UTC, merged