Tanfolyam leírás update
kir-dev/blog-next pull request #473
Opened 2023-02-22 13:27 UTC by DannySS123

2023-02-22 14:57 UTC, kisbogdan-kolos approved these changes

2023-02-22 15:06 UTC, berenteb submitted a review, later dismissed

2023-02-22 18:45 UTC, Tschonti requested changes

2023-02-22 18:45 UTC, Tschonti commented on src/content/courses/react-typescript.yaml
> +  HTML, CSS és TypeScript tudásunk felhasználásával megismerkedünk az egyik legnépszerűbb ReactJS keretrendszerrel,
HTML, CSS és TypeScript tudásunk felhasználásával megismerkedünk az egyik legnépszerűbb frontend keretrendszerrel, a ReactJS-szel.

2023-02-22 18:45 UTC, Tschonti commented on src/content/courses/webes-alapozo.yaml
> +  A tanfolyamon ismerkedhettek a modern szoftverfejlesztési módszerekekkel és technikákkel,
technikákkal

2023-02-22 20:59 UTC, Tschonti approved these changes

2023-02-23 16:14 UTC, berenteb commented
@DannySS123 lessssgo

2023-02-23 17:02 UTC, merged